module = (_ def _)* ~"$"
def = function / function_import

function           = "function" _ identifier _
                            lpar _
                            function_arguments _
                            function_retvals _
                            rpar
                            _ multi_exp _
                       "end" _ "function"

function_import    = _ "function" _ identifier _  "[" _ type_list _ function_retvals _ "]" _

function_arguments = args_groups_list / _

function_retvals   = ("returns" _ type_list) / _
type_list          = type (_ "," _ type)*

args_groups_list   = arg_def_group (_ ";" _ arg_def_group)*

arg_def_group      = arg_def_list _ ":" _ type

let                = "let" _ statements _ "in" _ multi_exp _ "end" _ "let"

if                 = "if" _ exp_singular _ "then" _
                        multi_exp _
                        ("elseif" _ exp_singular _ "then" _ multi_exp _)*
                        (_ "else" _ multi_exp )? _
                     "end" _ "if"

arg_def_list       = identifier (_ "," _ identifier)*

old                = "old" _ identifier

identifier         = ~"[a-z_][a-z0-9_]*"i

number_literal     = number_literal_int / number_literal_real
number_literal_int = ~"[0-9]+"
number_literal_real= ~"[0-9]*.[0-9]+"

exp_singular       = loop / if / let / array_access/ equation  /  algebraic / brackets_algebraic / builtin_call / call  / old   / identifier / number_literal

multi_exp          = exp_singular (_ "," _ exp_singular)*

builtin_call       = !("function" _) builtin    _ lpar _ multi_exp _ rpar
builtin            = "size"
call               = !("function" _) identifier _ lpar _ multi_exp _ rpar

operand            = if / let / loop /  brackets_algebraic / old / array_access / builtin_call / call / identifier / number_literal
equation           = operand _ "=" _ operand
algebraic          = (operand) (_ bin_op _ operand)+
brackets_algebraic = lpar _ algebraic _ rpar

lpar               = "("
rpar               = ")"
empty              = ""

_                  = ~"\s*"

bin_op             = "+" / "-" / "<="/ ">=" / "<" / ">" / "*" / "/" / "^" / "||" / "|"

array              = "array" _ "of" _ type
type               = array / std_type


array_exp          = brackets_algebraic / builtin_call / call / old / identifier
array_index        = algebraic / brackets_algebraic / builtin_call / call / old / identifier / number_literal

array_access       = array_exp (_ "[" _ array_index _"]")+

#array_access       = array_exp _ "[" _ array_index _"]"

# loops:

loop               = "for" _ range? _ initial? _ while? _ returns? _ "end" _ "for"
range              = range_scatter / range_numeric
 range_scatter     = identifier _ "in" _ exp_singular
 range_numeric     = identifier _ "in" _ exp_singular _ "," _ exp_singular
initial            = "let" _ statements
while              = while_do / do_while
while_do           = "while" _ exp_singular _ "do" _ statements
do_while           = "do" _ exp_singular _ "while" _ statements
returns            = "returns" _ reduction

statement          = assignment / dummy
dummy              = "dummy"
statements         = (statement _ )*
assignment         = identifier _ ":=" _ exp_singular _ (";" / _)

reduction          = reduction_type _ "of" _ multi_exp (_ "when" _ exp_singular)?

reduction_type     = "array" / "value" / "sum"

std_type           = integer_type / real_type / bool_type
integer_type       = "integer"
real_type          = "real"
bool_type          = "boolean"
